### ISSUE TITLE
Not working need ./config.json

### ISSUE THREAD

**Issue by Domantas357** [c3duan/Swag-Bot#3]
so?

**Comment by c3duan** [comment]
You need your own config.json with your own api keys for various apis

**Comment by UltimatumGamer** [comment]
Is there an Example with no 'entrys'?

**Comment by c3duan** [comment]
What do you mean by no 'entrys'? Can you specify?

**Comment by Valdex** [comment]
Who can send example config.json

**Comment by Brahaha1435** [comment]
hey bro, can u send your config.json and erase your api keys and token? just replace them with a description of what they were. thanks! if you want to use my bot, my username is brahaha#1435 in discord

**Comment by c3duan** [comment]
For sure, I will do that by this week

**Comment by c3duan** [comment]
I just uploaded an example config file named 'example-config.json'

**Comment by Brahaha1435** [comment]
thanks! you can try out one of my bots: https://discordapp.com/api/oauth2/authorize?client_id=583366572530204683&permissions=2146958833&scope=bot
